FROM ubuntu
RUN apt-get update
RUN apt-get install nginx -y
# WORKDIR /var/www/html/
WORKDIR /var/www/html/
COPY index.html  index.html 
# open up the port
EXPOSE 80
# disable nginx daemon
CMD ["nginx","-g","daemon off;"]